import express from 'express';
import * as tradingAlertController from '../controllers/v1/admin/tradingAlert.controller.js';
import { apiLimiter, readLimiter } from '../middlewares/rateLimiter.middleware.js';
const router = express.Router();
router.get('/partial-closes', readLimiter, tradingAlertController.listPartialCloses);
router.get('/', readLimiter, tradingAlertController.getAllAlerts);
router.get('/:id', readLimiter, tradingAlertController.getAlertById);
router.post('/', apiLimiter, tradingAlertController.createAlert);
router.post('/:id/partial-close', apiLimiter, tradingAlertController.partialCloseAlert);
router.post('/:id/full-close', apiLimiter, tradingAlertController.fullCloseAlert);
router.post('/:id/notify', apiLimiter, tradingAlertController.notifyAlertEvent);
router.put('/:id', apiLimiter, tradingAlertController.updateAlert);
router.delete('/:id', apiLimiter, tradingAlertController.deleteAlert);
export default router;
